# reusable config stanzas
only-release-tags: &only-release-tags
  filters:
    tags:
      only: /v[0-9]+\.[0-9]+\.[0-9]+.*/
    branches:
      ignore: /.*/

# start of config
version: 2.1

executors:
  nodejs:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo

jobs:
  install:
    executor: nodejs
    steps:
      - checkout
      - run:
          name: Configuring NPM authentication
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  lint:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm run lint
  test:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  build:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./
  publish:
    executor: nodejs
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Configuring NPM authentication
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN_PUBLISHING}" >> ~/.npmrc
      - run: npm publish

workflows:
  version: 2

  Test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - build:
          requires:
            - install

  Release:
    jobs:
      - install:
          <<: *only-release-tags
      - lint:
          <<: *only-release-tags
          requires:
            - install
      - test:
          <<: *only-release-tags
          requires:
            - install
      - build:
          <<: *only-release-tags
          requires:
            - install
      - publish:
          <<: *only-release-tags
          requires:
            - lint
            - test
            - build
